### ISSUE TITLE
Miscellaneous Cleanup 

### ISSUE THREAD

**Issue by J-Graham** [milestechnologies/ngx-keyboard-shortcuts#127]
- [x] Update the title of the demo app (Keyboard Shortcuts Demo)
- [x] Get a favicon
- [x] Review JSDoc comments
- [x] Review Demo Site

**Comment by markv2311** [comment]
We have a Favicon but we could not get it to work, if you could help with that as well?

**Comment by markv2311** [comment]
Title of Demo app updated
