### ISSUE TITLE
ReadMe Needs Updating

### ISSUE THREAD

**Issue by TAndraCode** [milestechnologies/ngx-keyboard-shortcuts#138]
ReadMe says demo can be accessed immediately in LocalHost:4200 which it cant. Need to find a clear way to display this so that a user can see what the package does.

**Comment by J-Graham** [comment]
Updated to the following to point out that npm install needs to happen first:

> To access direct implementations of ngx-keyboard-shortcuts (demos), you're required to either clone or download the repository onto your machine. Next run npm install, then npm start to run the demo project, which can then be accessed via localhost:4200.
