### ISSUE TITLE
couple of broken github links on README on https://www.npmjs.com/package/ngx-keyboard-shortcuts

### ISSUE THREAD

**Issue by ivarcode** [milestechnologies/ngx-keyboard-shortcuts#148]

**Comment by chriscamac** [comment]
Hi @ivarcode.  Can you be more specific about which links are broken?

Also, feel free to do a pull request for this if you feel so inclined.

**Comment by ivarcode** [comment]
I don't think a source code change (pull request) would be useful, since the problem is on the npmjs.com package page, the contributors link, for example, points to this address
https://github.com/milestechnologies/ngx-keyboard-shortcuts/blob/HEAD/%5Bhttps:/github.com/milestechnologies/ngx-keyboard-shortcuts/graphs/contributors%5D(https:/github.com/milestechnologies/ngx-keyboard-shortcuts/graphs/contributors)

instead of where it should
https://github.com/milestechnologies/ngx-keyboard-shortcuts/graphs/contributors

but thats just the one link, the license file too, is broken, and maybe others.  just wanted to point it out.

**Comment by chriscamac** [comment]
Roger That!

Thanks for the info.  I'm sure we can get this addressed.  Adding it in the task #147
