### ISSUE TITLE
Add Green Keeper support

### ISSUE THREAD

**Issue by J-Graham** [milestechnologies/ngx-keyboard-shortcuts#160]
https://greenkeeper.io/

**Comment by chriscamac** [comment]
This is a good idea, but I'm not too familiar with it.  @J-Graham have you used this in the past?  Can we discuss further so I know what kind of work is involved?

**Comment by notcaring42** [comment]
@chriscamac I can't do anything on my side with this. Here's what we need to do for the Miles org:

1. Visit [this link](https://github.com/apps/greenkeeper) to install it
2. Specify which repositories it needs to check

As long as the CI pipeline runs and returns a status for pull requests (which looking at the Azure CI yml it does), then greenkeeper should take it from there.
