### ISSUE TITLE
add settings.yml to define labels

### ISSUE THREAD

**Issue by chriscamac** [milestechnologies/ngx-keyboard-shortcuts#162]
this github app has been added to the milestechnologies account.  We need to setup a settings.yml file to make use of it.  https://probot.github.io/apps/settings/

**Comment by chriscamac** [comment]
planned steps:
- take note of all the issue labels as exist now and which issues have which labels
- remove all labels
- add settings.yml as described in documentation
- setup to handle labels
  - add back all that were there before
- once verified and working, then relabel all issues
- create issues in the other package repos to implement same solution

**Comment by belzaaron** [comment]
Pull request open: #164
