### ISSUE TITLE
taking files from gitlab, recreate them 

### ISSUE THREAD

**Issue by amassariiv** [milestechnologies/ngx-keyboard-shortcuts#20]
@chriscamac 
Take  Keyboard Shortcut Services and Directives +
 Help Window - tabled 
“karma.conf.js” and “test.ts”
 “Keyboard-shortcut.service.ts”
NgZone
package.JSON
Dependencies only
and recreate them for this github

**Comment by amassariiv** [comment]
for Tyler

**Comment by chriscamac** [comment]
This is a duplicate
