### ISSUE TITLE
add to helpwindowservice is window showing t/f

### ISSUE THREAD

**Issue by amassariiv** [milestechnologies/ngx-keyboard-shortcuts#42]
we've set the swalistance public, we would like to set it to private.
The swalInstance is initially private, to keep it this way we would like to have a boolean value that can be checked, if true the window is showing, if false the window is not showing. Need to change Swal so that it marks as false onClose.

**Comment by chriscamac** [comment]
This feature is changing and this issue won't be needed after the change.
